name: release-changesets

on:
   push:
      branches:
         - main

jobs:
   release:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Repo
           uses: actions/checkout@v4
           with:
              fetch-depth: 0

         - uses: actions/setup-node@v4
           with:
              node-version: 20

         - run: pnpm install --frozen-lockfile
         - run: pnpm build

         - uses: changesets/action@v1
           with:
              publish: pnpm changeset publish
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
